server:
  port: 10088
spring:
  application:
    name: ydbspaceUser
  datasource:
    url: jdbc:mysql://1.116.162.163:3306/webcloud?useSSL=false
    username: codimd
    password: Tan19970925!
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # Redis服务器地址
    host: 1.116.162.163
    # Redis数据库索引（默认为0）
    database: 5
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ydbspace
    # 连接超时时间
    timeout: 1000ms

logging:
  level:
    com.xn2001: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka