springfox:
  documentation:
      enabled: false  #关闭swagger
server:
  port: 5300
spring:
  #  设置文件上传大小
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  application:
    name: ydbspaceimage
  datasource:
    url: jdbc:mysql://1.116.162.163:3306/webcloud?useSSL=false
    username: codimd
    password: Tan19970925!
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: ydb
    virtual-host: /
  redis:
    # Redis服务器地址
    host: 1.116.162.163
    # Redis数据库索引（默认为0）
    database: 7
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ydbspace
    # 连接超时时间
    timeout: 1000ms
logging:
  level:
    com.xn2001: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  instance:
    instance-id: 自测
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

mybatis-plus:
  mapper-locations: classpath*:xml/*.xml
  configuration:
    #数据库驼峰命名转换
    map-underscore-to-camel-case: false
#调用rabbitmq
ydb:
  rabbitmq:
    exchangname: deletechange
    emailQueue: deletequeue
    fanout: true
#    fastdfs
#  注意这个trackerList：如果是集群tracker的话以逗号分隔开就行
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  trackerList: 服务器tracker的ip:22122
  thumb-image:
    width: 150
    height: 150
  pool:
    max-total: 200


#日志系统
  logstash:
    host: 1.116.162.163
  logging:
    level:
      root: info