server:
  port: 3056
spring:
  application:
    name: fileRedis
  redis:
    # Redis服务器地址
    host: 192.168.3.89
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ydbspace
    # 连接超时时间
      # 连接超时时间
    timeout: 6000
    lettcure:
      cluster:
        refresh:
          #          2.3版本以上才有效果开启拓扑刷新
          adaptive: true
          #          Lettuce 会每隔 60 秒检查一次集群状态，如果发现集群状态有变化，就会执行拓扑刷新操作
          period: 60s
      pool:
        max-active: 500
        #    //定义了连接池中最大空闲连接数，也就是连接池中最多允许存在的空闲连接数。
        max-idle: 500
        max-wait: 500
        min-idle: 0
      timeout: 500



