springfox:
  documentation:
      enabled: false  #关闭swagger

server:
  port: 5300
spring:
  application:
    name: ydbspaceimage
  datasource:
    url: jdbc:mysql://1.116.162.163:3306/webcloud?useSSL=false
    username: codimd
    password: Tan19970925!
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: ydb
    virtual-host: /
  redis:
    # Redis服务器地址
    host: 1.116.162.163
    # Redis数据库索引（默认为0）
    database: 7
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Aa1997925+
    # 连接超时时间
    timeout: 6000
    lettcure:
      cluster:
        refresh:
#          2.3版本以上才有效果开启拓扑刷新
          adaptive: true
#          Lettuce 会每隔 60 秒检查一次集群状态，如果发现集群状态有变化，就会执行拓扑刷新操作
          period: 60s
      pool:
        max-active: 500
        #    //定义了连接池中最大空闲连接数，也就是连接池中最多允许存在的空闲连接数。
        max-idle: 500
        max-wait: 500
        min-idle: 0
      timeout: 500
logging:
  level:
    com.xn2001: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
fdfs:
  connect-timeout: 30000
  so-timeout: 30000
  tracker-list: 1.116.162.163:22122
  pool:
    max-total: 800   # 连接池最大数量
    max-total-per-key: 200  # 单个tracker最大连接数
    max-wait-millis: 5000 # 连接耗尽最大等待时间 毫秒

#调用rabbitmq
ydb:
  rabbitmq:
    exchangname: deletechange
    emailQueue: deletequeue
    fanout: true
#    fastdfs

#日志系统
  logstash:
    host: 1.116.162.163
  logging:
    level:
      root: info