#公共配置可覆盖
spring:
 mvc:
  async:
   request-timeout: 60000

##自己的配置
user:
# 个人网盘配置策略
 wpfiletype: AliYunOpen
# 临时网盘配置策略
 sharefiletype: AliYunOpen
 devicdeid: 526997152

#security配置
server:
 servlet:
  session:
   cookie:
    name: ydbspace-webcloud #防止Cookie冲突，冲突会导致登录验证不通过

#配置文件注入也可以在代码里注入
# clientId：OAuth2客户端的ID。
# clientSecret：OAuth2客户端的密钥。
# accessTokenUri：OAuth2授权服务器的令牌端点URL。
# userAuthorizationUri：OAuth2授权服务器的授权端点URL。
# scope：OAuth2客户端请求的范围。
security:
 oauth2: #与oauth2-server对应的配置
  client:
#   OAuth2客户端的ID。在认证服务器配置过
   client-id: read
   client-secret: read
   user-authorization-uri: ${oauth2-server-url}/oauth/authorize
   access-token-uri: ${oauth2-server-url}/oauth/token
  resource:
   token-info-uri: ${oauth2-server-url}/oauth/check_token
   id: ${spring.application.name}  # 资源id，可能存在多个资源服务器，可以配置客户端拥有哪些资源的访问权限


#无用配置
resource:
 jwt:
  key-uri: ${oauth2-server-url}/oauth/token_key
mybatis-plus:
 mapper-locations: classpath*:xml/*.xml
 configuration:
  #数据库驼峰命名转换
  map-underscore-to-camel-case: false
#设置通用
eureka:
 instance:
   # 如果x秒内，依然没有收到续约请求，判定服务过期,默认90s
   lease-expiration-duration-in-seconds: 10
   # 每隔x秒钟，向服务中心发送一条续约指令,默认30s
   lease-renewal-interval-in-seconds: 10


## spring boot admin
management:
 endpoint:
  health:
   show-details: always
 endpoints:
  enabled-by-default: true
  web:
   base-path: /actuator
   exposure:
    include: '*'