name: master发部到腾讯云1
#设置触发条件
on:
  push:
    branches:
      - master
  # 手动触发部署
  workflow_dispatch:
#执行任务
jobs:
  build:
    #执行环境
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
  env:
#todo1    部署到服务器目录
    DEPLOY_PATH: /docker/ydbspace_github
# todo2   执行shell脚本名称
    DEPLOY_SHNAME: startgithub.sh
    steps:
      - name: 拉去最新的代码
        uses: actions/checkout@v3
      - name: 设置jdk
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: 项目打包
        run: mvn -B clean package -Dmaven.test.skip=true
        # - name: 删除旧的jar包以及运行脚本
        #         run: sshpass -p ${{secrets.REMOTE_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "cd /root/GitHub_Action && rm -rf ./*"
      - name: 上传jar包和启动脚本到服务器中
#todo3        部署那些jar包及拷贝运行shell
        run: sshpass -p ${{secrets.REMOTE_PASSWD}} scp -r -o StrictHostKeyChecking=no ./ydbspace_image/target/ydbspace_image.jar ./eurekaservice/target/eurekaservice.jar ./fileMq/target ./User/target/User.jar  ./部署/$DEPLOY_SHNAME root@${{secrets.REMOTE_IP}}:$DEPLOY_PATH

      - name: 启动项目
        run: sshpass -p ${{secrets.REMOTE_PASSWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "  cd $DEPLOY_PATH && ./$DEPLOY_SHNAME start"
